import { Document, Page, Text, View } from '@react-pdf/renderer'
import { sharedStyles, formatPdfDate } from './shared-styles'

interface CoverSheetProps {
  taxpayerName: string
  tin: string
  rdoCode: string
  address: string
  zipCode: string
  taxYear: number
  electedRate: string | null
  totalGross: string
  totalCwt: string
  filedCount: number
  totalCount: number
}

export function CoverSheet({
  taxpayerName,
  tin,
  rdoCode,
  address,
  zipCode,
  taxYear,
  electedRate,
  totalGross,
  totalCwt,
  filedCount,
  totalCount,
}: CoverSheetProps) {
  return (
    <Document>
      <Page size="A4" style={sharedStyles.page}>
        <Text style={sharedStyles.title}>Kuwenta Filing Package</Text>
        <Text style={sharedStyles.subtitle}>Tax Year {taxYear}</Text>

        <View style={sharedStyles.section}>
          <Text style={sharedStyles.sectionTitle}>Taxpayer Information</Text>
          <View style={sharedStyles.twoCol}>
            <View style={sharedStyles.col}>
              <Text><Text style={sharedStyles.label}>Name: </Text>{taxpayerName}</Text>
              <Text><Text style={sharedStyles.label}>TIN: </Text>{tin}</Text>
              <Text><Text style={sharedStyles.label}>RDO: </Text>{rdoCode}</Text>
            </View>
            <View style={sharedStyles.col}>
              <Text><Text style={sharedStyles.label}>Address: </Text>{address}</Text>
              <Text><Text style={sharedStyles.label}>ZIP: </Text>{zipCode}</Text>
              <Text><Text style={sharedStyles.label}>Rate Election: </Text>{electedRate === 'RATE_8PCT' ? '8% Flat Rate' : 'Graduated Rate'}</Text>
            </View>
          </View>
        </View>

        <View style={sharedStyles.section}>
          <Text style={sharedStyles.sectionTitle}>Year-to-Date Summary</Text>
          <View style={sharedStyles.row}>
            <Text>Total Gross Receipts</Text>
            <Text style={sharedStyles.value}>{totalGross}</Text>
          </View>
          <View style={sharedStyles.row}>
            <Text>Total CWT Withheld</Text>
            <Text style={sharedStyles.value}>{totalCwt}</Text>
          </View>
          <View style={sharedStyles.row}>
            <Text style={sharedStyles.label}>Returns Filed</Text>
            <Text style={[sharedStyles.value, sharedStyles.label]}>{filedCount} of {totalCount}</Text>
          </View>
        </View>

        <Text style={sharedStyles.disclaimer}>
          This filing package was generated by Kuwenta on {formatPdfDate(new Date())}.
          Validate all forms against official BIR systems before submission.
        </Text>
      </Page>
    </Document>
  )
}
