import { Document, Page, Text, View } from '@react-pdf/renderer'
import {
  sharedStyles,
  formatPdfPeso,
  formatPdfDate,
} from '../shared-styles'

export interface IncomeSummaryRow {
  quarter: number
  payorName: string
  payorTin: string
  atcCode: string
  gross: string
  cwt: string
}

export interface IncomeSummaryPdfProps {
  taxpayer: {
    fullName: string
    tin: string
    rdoCode: string
  }
  taxYear: number
  rows: IncomeSummaryRow[]
  totalGross: string
  totalCwt: string
}

export function IncomeSummaryPdf({
  taxpayer,
  taxYear,
  rows,
  totalGross,
  totalCwt,
}: IncomeSummaryPdfProps) {
  const sorted = [...rows].sort((a, b) => {
    if (a.quarter !== b.quarter) return a.quarter - b.quarter
    const p = a.payorName.localeCompare(b.payorName)
    if (p !== 0) return p
    return a.atcCode.localeCompare(b.atcCode)
  })

  return (
    <Document>
      <Page size="A4" style={sharedStyles.page}>
        <Text style={sharedStyles.title}>Consolidated Income Summary</Text>
        <Text style={sharedStyles.subtitle}>BIR Form 2307 — Tax Year {taxYear}</Text>

        <View style={sharedStyles.section}>
          <Text style={sharedStyles.sectionTitle}>Taxpayer Information</Text>
          <View style={sharedStyles.twoCol}>
            <View style={sharedStyles.col}>
              <Text><Text style={sharedStyles.label}>Name: </Text>{taxpayer.fullName}</Text>
              <Text><Text style={sharedStyles.label}>TIN: </Text>{taxpayer.tin}</Text>
              <Text><Text style={sharedStyles.label}>RDO: </Text>{taxpayer.rdoCode}</Text>
            </View>
            <View style={sharedStyles.col}>
              <Text><Text style={sharedStyles.label}>Total Gross: </Text>{formatPdfPeso(totalGross)}</Text>
              <Text><Text style={sharedStyles.label}>Total CWT: </Text>{formatPdfPeso(totalCwt)}</Text>
              <Text><Text style={sharedStyles.label}>Certificates: </Text>{rows.length}</Text>
            </View>
          </View>
        </View>

        <View style={sharedStyles.section}>
          <Text style={sharedStyles.sectionTitle}>2307 Certificates</Text>
          <View style={sharedStyles.table}>
            <View style={[sharedStyles.tableRow, sharedStyles.tableHeader]}>
              <Text style={[sharedStyles.tableCell, { flex: 0.6 }]}>Q</Text>
              <Text style={[sharedStyles.tableCell, { flex: 2.4 }]}>Payor</Text>
              <Text style={[sharedStyles.tableCell, { flex: 1.2 }]}>ATC</Text>
              <Text style={[sharedStyles.tableCell, { flex: 1.4, textAlign: 'right' }]}>Gross</Text>
              <Text style={[sharedStyles.tableCell, { flex: 1.4, textAlign: 'right' }]}>CWT</Text>
            </View>
            {sorted.map((row, idx) => (
              <View key={`${row.quarter}-${row.payorTin}-${row.atcCode}-${idx}`} style={sharedStyles.tableRow}>
                <Text style={[sharedStyles.tableCell, { flex: 0.6 }]}>Q{row.quarter}</Text>
                <Text style={[sharedStyles.tableCell, { flex: 2.4 }]}>
                  {row.payorName} ({row.payorTin})
                </Text>
                <Text style={[sharedStyles.tableCell, { flex: 1.2 }]}>{row.atcCode}</Text>
                <Text style={[sharedStyles.tableCell, { flex: 1.4, textAlign: 'right' }]}>
                  {formatPdfPeso(row.gross)}
                </Text>
                <Text style={[sharedStyles.tableCell, { flex: 1.4, textAlign: 'right' }]}>
                  {formatPdfPeso(row.cwt)}
                </Text>
              </View>
            ))}
            {sorted.length === 0 && (
              <Text style={{ marginTop: 8, color: '#666' }}>No 2307 certificates on file.</Text>
            )}
            {sorted.length > 0 && (
              <View style={[sharedStyles.tableRow, { fontFamily: 'Helvetica-Bold', marginTop: 4 }]}>
                <Text style={[sharedStyles.tableCell, { flex: 4.2 }]}>Totals</Text>
                <Text style={[sharedStyles.tableCell, { flex: 1.4, textAlign: 'right' }]}>
                  {formatPdfPeso(totalGross)}
                </Text>
                <Text style={[sharedStyles.tableCell, { flex: 1.4, textAlign: 'right' }]}>
                  {formatPdfPeso(totalCwt)}
                </Text>
              </View>
            )}
          </View>
        </View>

        <Text style={sharedStyles.disclaimer}>
          Generated by Kuwenta on {formatPdfDate(new Date())}. This summary is a
          BIR Form 2307 attachable for the 1701A annual return. Validate all
          values against official BIR systems before submission.
        </Text>
      </Page>
    </Document>
  )
}
